AWSTemplateFormatVersion: '2010-09-09'
Description: "Infrastructura ECS Fargate pe VPC si Subnet Default"

Parameters:
  EcrRepositoryName:
    Type: String
    Description: "Numele repository-ului ECR creat manual"

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: "ID-ul unui Subnet Public din VPC-ul Default"

Resources:
  # 1. IAM Execution Role
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # 2. Security Group
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite acces pe portul 5050"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5050
          ToPort: 5050
          CidrIp: 0.0.0.0/0

  # 3. Cluster ECS
  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "proiectul-meu-cluster"

  # 4. Task Definition
  MyECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "proiectul-meu-task"
      RequiresCompatibilities:
        - "FARGATE"
      NetworkMode: awsvpc
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: "aplicatie-container"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepositoryName}:latest"
          Essential: true
          PortMappings:
            - ContainerPort: 5050
              Protocol: tcp

  # 5. ECS Service
  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: "proiectul-meu-service"
      Cluster: !Ref MyECSCluster
      TaskDefinition: !Ref MyECSTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref "SubnetId"
          SecurityGroups:
            - !Ref "ECSSecurityGroup"