Description: 'Stack 3: ECS Cluster, Task Definition and Service'

Parameters:
  EnvironmentName:
    Description: Name Projects
    Type: String
    Default: ScalabilitySolution

Resources:
  # CLUSTER
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvironmentName}-Cluster"

  # LOG GROUP
  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${EnvironmentName}"
      RetentionInDays: 7

# THE MISSING PIECE: ECS Task Execution Role
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-ECSTaskExecutionRole"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # TASK DEFINITION
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentName}-Task"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: !Sub "${EnvironmentName}-ContainerApp"
          Image: 029139774173.dkr.ecr.eu-central-1.amazonaws.com/repository-codeapp:latest
          PortMappings:
            - ContainerPort: 5050
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  # ECS SERVICE
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${EnvironmentName}-Service"
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1 #cate containere ruleaza
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            Fn::Split: [",", { "Fn::ImportValue": !Sub "${EnvironmentName}-PrivateSubnetsID" }]
          SecurityGroups:
            - Fn::ImportValue: !Sub "${EnvironmentName}-CLUSTER-SecurityGroup"
      LoadBalancers:
        - ContainerName: !Sub "${EnvironmentName}-ContainerApp"
          ContainerPort: 5050
          TargetGroupArn:
            Fn::ImportValue: !Sub "${EnvironmentName}-TargetGroup-ARN"

Outputs:
  ServiceArn:
    Description: ARN-ul serviciului ECS
    Value: !Ref ECSService

  ECSClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${EnvironmentName}-ClusterName"

    ECSServiceName:
      Value: !GetAtt ECSService
      Export:
        Name: !Sub "${EnvironmentName}-ServiceName"

  ECSResourceIdForScaling:
    Description: Resource ID for Application Auto Scaling
    Value: !Sub "service/${ECSCluster}/${ECSService.Name}"
    Export:
      Name: !Sub "${EnvironmentName}-ScalingResourceId"

